name: accept latest screenshots

on:
  push:
    branches:
      - 'main'
    paths:
      - 'actions/accept_screenshots.json'

jobs:
  accept-screenshots:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: npm i blink-diff
    - name: copy latest screenshots to accepted folder
      run: node actions/accept_screenshots.js
    - name: Commit and push
      if: ${{ false }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Accepted latest visual tests
