name: accessibility evaluation

on:
  push:
    paths:
      - 'projects.json'

jobs:
  accessibility-evaluation:

    name: accessibility-evaluation-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    container: buildkite/puppeteer

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i pa11y
    - name: Evaluation
      run: node evaluate.js
    - name: Commit and push
      if: ${{ true }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated accessibuility test
        